api/urls.py
from django.urls import path
from .views.accounts import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomUserLoginView

urlpatterns = [
    path('', CustomUserLoginView.as_view(), name='login'),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('owner/', include('owner.urls')),
    path('parent/<int:pk>/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
]

parent/urls.py
from django.urls import path
from .views import ParentDashboardView, SwitchStudentView
from accounts.views import StudentSignUpView
from report_card.views import ReportCardDetailView
from report.views import ReportListView
from vocabulary_test.views import VocabularyTestDetailView
from test_result.views import TestResultDetailView
from regular_lesson.views import ParentLessonListView
from notification.views import NotificationListView
from special_lesson.views import SpecialLessonListView, SpecialLessonStudentRequestFormView
from year_schedule.views import ParentYearScheduleView
from file.views import FileDetailView, FileListView
from accounts.views import CustomUserProfileView, ChangePasswordView

app_name = 'parent'

urlpatterns = [
    # path('', ParentDashboardView.as_view(), name='dashboard'),

    path('account/', CustomUserProfileView.as_view(), name='account_profile'),
    path('account/change_password/', ChangePasswordView.as_view(), name='account_change_password'),

    path('test_result/', TestResultDetailView.as_view(), name='test_result_detail'),

    path('report/', ReportListView.as_view(), name='report_detail'),

    path('report_card/', ReportCardDetailView.as_view(), name='report_card_detail'), 

    path('vocabulary_test/', VocabularyTestDetailView.as_view(), name='vocabulary_test_detail'),

    path('switch_student/', SwitchStudentView.as_view(), name='switch_student'),

    path('notification/', NotificationListView.as_view(), name='notification_list'),

    path('lesson/', ParentLessonListView.as_view(), name='schedule_list'),

    path('year_schedule/', ParentYearScheduleView.as_view(), name='dashboard'),

    path('special/', SpecialLessonListView.as_view(), name='special_lesson_list'),
    path('special/<int:special_lesson_pk>/', SpecialLessonStudentRequestFormView.as_view(), name='special_lesson_request'),

    path('file/', FileListView.as_view(), name='file_list'),
    path('file/<int:file_pk>/', FileDetailView.as_view(), name='file_detail'),

    path('student_signup/', StudentSignUpView.as_view(), name='student_signup'),
]

teacher/urls.py
from django.urls import path
from .views import TeacherDashboardView
from students.views import StudentNotableListView, StudentNotableCreateView, StudentNotableUpdateView, StudentNotableDeleteView, StudentSelectView, TeacherStudentListView
from report_card.views import ReportCardDetailView
from report.views import ReportListView, TeacherSubmitReportListView, SubmitVocabularyTestCreateView, SubmitReportUpdateView, SubmitReportCreateView
from vocabulary_test.views import VocabularyTestDetailView, VocabularyTestUpdateView
from test_result.views import TestResultDetailView
from special_lesson.views import SpecialLessonListView, SpecialLessonTeacherRequestFormView
from shift.views import ShiftDetailDisplayView, ShiftSelectView
from file.views import FileListView, FileDetailView
from year_schedule.views import  TeacherYearScheduleView
from accounts.views import ChangePasswordView, CustomUserProfileView

app_name = 'teacher'

urlpatterns = [
    path('', TeacherYearScheduleView.as_view(), name='dashboard'),

    path('account/', CustomUserProfileView.as_view(), name='account_profile'),
    path('account/change_password/', ChangePasswordView.as_view(), name='account_change_password'),

    path('submit_report/', TeacherSubmitReportListView.as_view(), name='submit_report_list'),
    path('submit_report/<int:pk>/', SubmitReportCreateView.as_view(), name='submit_report'),
    path('submit_report/<int:pk>/edit/', SubmitReportUpdateView.as_view(), name='submit_report_edit'),
    path('submit_report/vocabulary_test/', SubmitVocabularyTestCreateView.as_view(), name='submit_vocabulary_test'),

    path('student/', TeacherStudentListView.as_view(), name='document_list'),
    path('student/<int:pk>/', StudentSelectView.as_view(), name='document_select'),
    path('student/<int:pk>/notable/', StudentNotableListView.as_view(), name='student_notable_list'),
    path('student/<int:pk>/notable/create/', StudentNotableCreateView.as_view(), name='student_notable_create'),
    path('student/<int:pk>/notable/update/', StudentNotableUpdateView.as_view(), name='student_notable_update'),
    path('student/<int:pk>/notable/delete/', StudentNotableDeleteView.as_view(), name='student_notable_delete'),
    path('student/<int:pk>/test_result/', TestResultDetailView.as_view(), name='test_result_detail'),
    path('student/<int:pk>/report/', ReportListView.as_view(), name='report_detail'),
    path('student/<int:pk>/report_card/', ReportCardDetailView.as_view(), name='report_card_detail'), 
    path('student/<int:pk>/vocabulary_test/', VocabularyTestDetailView.as_view(), name='vocabulary_test_detail'),
    path('student/<int:pk>/vocabulary_test/update/', VocabularyTestUpdateView.as_view(), name='vocabulary_test_update'),

    path('shift/', ShiftSelectView.as_view(), name='shift_select'),
    path('shift/<int:year>/<int:week>/<int:day>/', ShiftDetailDisplayView.as_view(), name='shift_display'),

    path('special/', SpecialLessonListView.as_view(), name='special_lesson_list'),
    path('special/<int:pk>/', SpecialLessonTeacherRequestFormView.as_view(), name='special_lesson_request'),

    path('file/', FileListView.as_view(), name='file_list'),
    path('file/<int:pk>/', FileDetailView.as_view(), name='file_detail'),
]

teacher/views.py
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, FormView
from django.urls import reverse_lazy

from accounts.decorators import user_type_required
from students.models import Student
from notification.models import Notification
from utils.choices import GRADE_CHOICES
from accounts.models import CustomUser
from accounts.forms import TeacherStatusForm

# 未使用
@method_decorator(user_type_required(), name='dispatch')
class TeacherDashboardView(TemplateView):
    template_name = 'teacher/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        notifications = Notification.objects.filter(user=self.request.user)  # すべての通知を取得
        context['notifications'] = notifications  # テンプレートコンテキストに通知データを追加
        return context
    

@method_decorator(user_type_required('owner'), name='dispatch')
class TeacherListView(ListView):
    model = CustomUser
    template_name = 'owner/teacher_list.html'
    context_object_name = 'teachers'

    def get_queryset(self):
        return CustomUser.objects.filter(is_teacher=True, is_active=True)

@method_decorator(user_type_required('owner'), name='dispatch')
class TeacherStatusUpdateView(FormView):
    template_name = 'owner/teacher_status_update.html'
    form_class = TeacherStatusForm

    def get_success_url(self):
        return reverse_lazy('owner:teacher_list')

    def get_initial(self):
        teacher = CustomUser.objects.get(pk=self.kwargs['pk'])
        profile = teacher.teacher_profile
        current_status = ''
        if profile.is_withdrawn:
            current_status = 'withdrawn'
        return {'status': current_status}

    def form_valid(self, form):
        teacher = CustomUser.objects.get(pk=self.kwargs['pk'])

        profile = teacher.teacher_profile
        # フォームから新しいステータスを取得
        new_status = form.cleaned_data['status']
        profile.is_withdrawn = False

        if new_status == 'withdrawn':
            profile.is_withdrawn = True
        
        # データベースに変更を保存
        profile.save()
        return super().form_valid(form)

teacher/templates/teacher/account_profile.html
{% extends 'teacher/base.html' %}

{% block title %}アカウント{% endblock %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>アカウント情報</h3>
        </div>
        <div class="card-body">
            <p class="card-text"><strong>氏名:</strong> {{ user }}</p>
            <p class="card-text"><strong>ユーザーネーム:</strong> {{ user.username }}</p>
            <p class="card-text"><strong>メールアドレス:</strong> {{ user.email }}</p>
            <p class="card-text"><strong>登録日時:</strong> {{ user.date_joined }}</p>
            <a href="{% url 'teacher:account_change_password' %}" class="btn btn-primary">パスワードの変更</a>
        </div>
    </div>
</div>
{% endblock %}

teacher/templates/teacher/dashboard.html
{% extends 'teacher/base.html' %}

{% block title %}ホーム{% endblock %}
{% block headline %}ホーム{% endblock %}

{% block content %}
    <ul>
        {% for notification in notifications %}
        <li>
            {{ notification.message }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

teacher/templates/teacher/document_select.html
{% extends 'teacher/base.html' %}

{% block title %}生徒資料{% endblock %}
{% block headline %}生徒資料{% endblock %}

{% block content %}
    <div class="container">
        <h4>{{ student }}の資料</h4>
        <div class="row">
            <div class="col-md-6">
                <div class="card border-primary mb-3">
                    <div class="card-header">テスト結果</div>
                    <div class="card-body text-primary">
                        <p class="card-text">{{ student }}のテスト結果を表示します。</p>
                        <a href="{% url 'teacher:test_result_detail' pk %}" class="btn btn-primary">確認</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card border-secondary mb-3">
                    <div class="card-header">通知簿</div>
                    <div class="card-body text-secondary">
                        <p class="card-text">{{ student }}の通知簿を表示します。</p>
                        <a href="{% url 'teacher:report_card_detail' pk %}" class="btn btn-secondary">確認</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card border-success mb-3">
                    <div class="card-header">授業報告書</div>
                    <div class="card-body text-success">
                        <p class="card-text">{{ student }}の報告書を表示します。</p>
                        <a href="{% url 'teacher:report_detail' pk %}" class="btn btn-success">確認</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card border-danger mb-3">
                    <div class="card-header">英単語テスト</div>
                    <div class="card-body text-danger">
                        <p class="card-text">{{ student }}の英単語テストの結果を表示します。</p>
                        <a href="{% url 'teacher:vocabulary_test_detail' pk %}" class="btn btn-danger">確認</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

teacher/templates/teacher/file_list.html
{% extends 'teacher/base.html' %}

{% block title %}ファイル{% endblock %}
{% block headline %}ファイル{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for file in files %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ file }}</h5>
                    {% if file.file %}
                        <p class="card-text">アップロード日: {{ file.created_at }}</p>
                        <a href="{% url 'teacher:file_detail' file.pk %}" class="btn btn-primary">確認</a>
                    {% else %}
                        <p class="card-text">No file uploaded</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

teacher/templates/teacher/notification_list.html
{% extends 'teacher/base.html' %}
{% block head %}
<style>
    .notification-filters {
  margin-bottom: 20px;
}

.filter-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  margin-right: 10px;
  cursor: pointer;
}

.notification-cards {
  display: flex;
  flex-direction: column; /* カードを縦に並べる */
  gap: 20px;
}

.notification-card {
  background-color: #fff;
  border: 2px solid transparent; /* 赤線の下に隠れています */
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  position: relative; /* アイコンを配置するため */
}

.notification-card.priority {
  border-color: red; /* 重要なメッセージのカードに赤線を付ける */
}

.priority-badge {
  color: red;
  top: 10px;
  left: 10px;
}

.unread {
  border: 2px solid #007bff;
}

.read-notification-form {
  margin-top: 10px;
}

.read-notification-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 5px 10px;
  cursor: pointer;
}

.read-notification-button:hover {
  background-color: #0056b3;
}

</style>
{% endblock %}
{% block content %}
  <h2>通知センター</h2>
  <form method="GET" action="{% url 'teacher:notification_list' %}" class="notification-filters">
    <button type="submit" name="is_priority" value="true" class="filter-button">重要</button>
    <button type="submit" name="is_read" value="true" class="filter-button">確認済み</button>
    <button type="submit" name="is_read" value="false" class="filter-button">新規メッセージ</button>
  </form>
  <div class="notification-cards">
    {% for notification in notifications %}
      <div class="notification-card {% if notification.is_priority %}priority{% endif %} {% if not notification.is_read %}unread{% endif %}">
        {% if notification.is_priority %}
          <span class="priority-badge"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z"/>
            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z"/>
          </svg>
          </span>
        {% endif %}
        <strong>{{ notification.message }}</strong>
        {% if not notification.is_read %}
        <form method="POST" action="{% url 'teacher:notification_list' %}" class="read-notification-form">
          {% csrf_token %}
          <input type="hidden" name="notification_id" value="{{ notification.pk }}">
          <button type="submit" class="read-notification-button">確認する</button>
        </form>
        {% endif %}
      </div>
    {% empty %}
      <div class="notification-card empty">
        <p>メッセージがありません</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

teacher/templates/teacher/report_detail.html
{% extends 'teacher/base.html' %}

{% block title %}授業報告書{% endblock %}

{% block head %}
<style>
    @media (max-width: 414px) {
        .table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 0px!important;
        }

        .table th, .table td {
            border: 1px solid #dee2e6;
            padding: 8px;
            text-align: center;
        }

        .table thead th {
            background-color: #f8f9fa;
            border-color: #dee2e6;
        }

        .table tbody tr:nth-of-type(even) {
            background-color: #f8f9fa;
        }

        .table tbody tr:hover {
            background-color: #e2e6ea;
        }

        .table tbody tr:last-child td:last-child {
            padding-right: 24px;
        }

        .border-none {
            border-bottom: 0!important;
        }

        .bold-font{
            font-weight: bold;
        }
    }
    @media screen and (max-width: 768px) {
        .table {
            font-size: 12px;
        }
    } 
</style>
{% endblock %}

{% block content %}
    <h1>授業報告書</h1>
    <form method="GET" action="" class="row mb-3 align-items-center">
        <div class="col-3">
            <label for="month_select" class="sr-only">月を選択:</label>
        </div>
        <div class="col-6">
            <select name="month" id="month_select" class="form-control">
                <option value="">すべての月</option>
            </select>
        </div>
        <div class="col-3">
            <button type="submit" class="btn btn-primary">検索</button>
        </div>
    </form>
    <div class="table-responsive m-0">
        {% for report in reports %}
            <table class="table" style="width: 600px;">
                <tbody>
                    <tr>
                        <td class="bold-font" style="width: 20%">時間</td>
                        <td style="width: 30%;">{{ report.lesson.date }} {{ report.lesson.get_time_display }} {% if report.lesson.rescheduled_date %}(振替先: {{ report.lesson.rescheduled_date }}{{ report.lesson.get_rescheduled_time_display }}){% endif %}</td>
                        <td class="bold-font" style="width: 20%;">担当講師</td>
                        <td style="width: 30%;">{{ report.teacher }}</td>
                    </tr>
                    <tr>
                        <td class="bold-font">教科</td>
                        <td>{% if report.lesson.is_regular or report.lesson.is_temporaly %}{{ report.lesson.get_subject_display }}{% else %}{{ report.lesson.get_subject_display }} ({{ report.lesson.special.special_lesson.name }}){% endif %}</td>
                        <td class="bold-font">単元</td>
                        <td>{{ report.unit }}</td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td colspan="1" class="bold-font">宿題を出したか</td>
                        <td colspan="1">{% if report.homework %}◯{% else %}×{% endif %}</td>
                        <td colspan="1" class="bold-font">宿題をやってきたか</td>
                        <td colspan="1">{% if report.homework_done %}◯{% else %}×{% endif %}</td>
                    </tr>
                    <tr>
                        <td colspan="1"class="bold-font">授業中の様子</td>
                        <td colspan="3">{{ report.behavior }}</td>
                    </tr>
                    <tr>
                        <td colspan="1"class="bold-font">改善点・苦手項目</td>
                        <td colspan="3">{{ report.weakness }}</td>
                    </tr>
                </tbody>
            </table>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    <script>
        // 月の選択肢を生成する関数
        function populateMonthSelect() {
            var select = document.getElementById("month_select");
            for (var i = 1; i <= 12; i++) {
                var option = document.createElement("option");
                option.text = i + "月";
                option.value = i;
                select.add(option);
            }
        }

        // ページが読み込まれた時に選択肢を生成する
        document.addEventListener("DOMContentLoaded", function() {
            populateMonthSelect();
        });
    </script>
{% endblock %}

teacher/templates/teacher/rooms.html
{% extends 'teacher/base.html' %}
{% block title %}Rooms | {% endblock %}
{% block content %}
<div class="container-lg mt-10">
    <div class="row">
        {% for room in rooms %}
        <div class="col-lg-12 mb-4">
            <div class="card border-0 rounded-3 shadow">
                <div class="card-body">
                    <h2 class="mb-4 text-2xl font-semibold">
                    {% if room.users.first.is_teacher %}
                    塾長
                    {% else %}
                    {{ room.users.first.first_name }} {{ room.users.first.last_name }}
                    {% endif %}
                    </h2>
                    {% if room.last_message %}
                    <p>{{ room.last_message.content }}</p>
                    {% endif %}
                    <a href="{% url 'teacher:room' room.slug %}" class="btn btn-primary btn-lg rounded-pill px-5">入る</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

teacher/templates/teacher/shift_calendar.html
{% extends 'teacher/base.html' %}

{% block title %}シフト{% endblock %}
{% block headline %}シフト{% endblock %}

{% block head %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js'></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap5@6.1.11/index.global.min.js"></script>
{% endblock %}

{% block style %}
    <style>
        #calendar a {
            color: black!important;
            text-decoration: none!important;
        }

        /* カレンダーのスタイル */
        #calendar {
            width: 100%;
            max-width: 100%;
            max-height: 800px;
        }

        .fc-toolbar-title {
            font-size: 16px!important;
        }
    </style>
{% endblock %}
  
{% block content %}
    <div id='calendar'></div>
{% endblock %}

{% block script %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // 今日の日付を取得
            var today = new Date();
            
            // 年度開始を3月にするため、年度開始日を設定
            var startOfYear = new Date(today.getFullYear(), 2, 1);
            
            // 今の日付が1月か2月の場合は年度を1年前に設定
            if (today.getMonth() === 0 || today.getMonth() === 1) {
                startOfYear.setFullYear(startOfYear.getFullYear() - 1);
            }
            
            // 年度終了日は次の年の2月末日とする
            var endOfYear = new Date(startOfYear.getFullYear() + 1, 2, 0);
            
            // 年度の開始日は3月1日、年度終了日は来年の2月末日とする
            var validRangeStart = startOfYear.getFullYear() + '-03-01';

            var validRangeEnd = endOfYear.getFullYear() + '-03-01';
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'listWeek',
                views: {
                    listWeek: {
                        buttonText: '週間',
                        allDayText: '',
                    }
                },
                headerToolbar: {
                    start: 'title',
                    end: 'prev,next'
                },
                locale: 'ja',
                noEventsContent: 'イベントはありません',
                validRange: {
                    start: validRangeStart,
                    end: validRangeEnd
                },
                events: {{ events|safe }},
                height: 'auto',
                eventOrder: 'start',
            });
            calendar.render();
        });
    </script>
{% endblock %}

teacher/templates/teacher/shift_display.html
{% extends 'teacher/base.html' %}
{% load custom_tags %}

{% block title %}シフト{% endblock %}

{% block head %}
<style>
    td {
        padding: 0!important;
    }

    hr {
        margin: 0!important;
        color: white;
    }

    table {
        width: {% if is_extend %}600{% else %}500{% endif %}px!important;
        font-size: 10px!important;
    }

    .td-row-upper, .td-row-lower {
        margin: 0!important;
        width: 100%;
    }

    .td-row-lower {
        border: 1px black solid;
        height: 14px;
    }

    .td-col {
        border: 1px black solid;
        padding: 0!important;
        height: 26px;
    }

    .page-link {
        font-size: 12px!important;
        padding: 3px;
    }

    td {
        font-size: 7px!important;
    }
  </style>
{% endblock %}

{% block content %}
<nav class="d-flex justify-content-center">
    <ul class="pagination">
        {% for date in dates %}
            <li class="page-item"><a class="page-link {% if forloop.counter == day %}active{% endif %}" href="{% url 'teacher:shift_display' year week forloop.counter %}">{{ date }}</a></li>
        {% endfor %}
    </ul>
</nav>
{% if shifts %}
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th></th>
                {% for time in time_choices %}
                <th class="text-center">
                    {{ time }}
                {% endfor %}
            </tr>
        </thead>
        <tbody>
        {% regroup shifts by room as room_list %}
        {% for room in room_list %}
                <tr>
                    <th class="text-center">{{ room.grouper }}</th>
                    {% for shift in room.list %}
                    <td>
                        <div class="row td-row-upper">
                            {% for i in '1234' %}
                            {% get_lesson shift i as lesson_obj %}
                            <div class="col-6 td-col text-center">
                                <div class="w-100 h-100 d-flex align-items-center flex-column justify-content-center
                                {% if not lesson_obj %}
                                    bg-white
                                {% elif lesson_obj.is_rescheduled %}
                                    bg-warning
                                {% elif lesson_obj.is_temporaly %}
                                    bg-light
                                {% elif lesson_obj.is_regular %}
                                    bg-white
                                {% else %}
                                    bg-info
                                {% endif %}
                                    ">
                                    <span>
                                        {{ lesson_obj.student }}
                                    </span>
                                    <span>
                                        {{ lesson_obj.get_grade_display }}
                                        {{ lesson_obj.get_subject_display }}
                                        
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>                                                           
                        <div class="row td-row-lower justify-content-center">
                            <div class="d-flex justify-content-center {% if not shift.teacher_shift %}{% if shift.lessons.lesson1 or shift.lessons.lesson2 or shift.lessons.lesson3 or shift.lessons.lesson4 %}bg-danger{% endif %}{% endif %}">
                                {% if shift.teacher_shift.is_fixed %}
                                <span>{{ shift.teacher_shift.fixed_shift.teacher }}</span>
                                {% else %}
                                <span>{{ shift.teacher_shift.temporaly_shift.teacher }}</span>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                    {% endfor %}
                </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <h1 class="text-center" style="color: red; font-size: 30px; margin-top: 250px;">休校日</h1>
{% endif %}
{% endblock %}

teacher/templates/teacher/special_list.html
{% extends 'teacher/base.html' %}

{% block title %}特別講習一覧{% endblock %}

{% block style %}
<style>
    p {
        margin-bottom: 0;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <ul class="list-group">
        {% for special_lesson in special_lessons %}
        <a href="{% url 'teacher:special_lesson_request' special_lesson.pk %}" class="text-decoration-none">
            <li class="list-group-item text-primary">
                <p>{{ special_lesson.name }}</p>
                <p>{{ special_lesson.start_date|date:"Y年m月d日" }}-{{ special_lesson.end_date|date:"Y年m月d日" }}</p>
            </li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

teacher/templates/teacher/student_notable_create.html
{% extends 'teacher/base.html' %}

{% block title %}生徒特筆事項追加{% endblock %}

{% block content %}
<div class="container mt-4">
    <h4>{{ student }}の特筆事項を追加</h4>
    
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">送信</button>
    </form>
</div>
{% endblock %}

teacher/templates/teacher/student_notable_list.html
{% extends 'teacher/base.html' %}

{% block title %}生徒特筆事項{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-9">
            <h4>{{ student }}の特筆事項</h4>
        </div>
        <div class="col-3">
            <a  class="btn btn-secondary" href="{% url 'teacher:student_notable_create' student.pk %}">追加</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">内容</th>
                <th>作成</th>
                <th>日付</th>
                <th>編集</th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
            {% for notable in notables %}
            <tr>
                <td>{{ notable.notable }}</td>
                <td>{{ notable.writer }}</td>
                <td>{{ notable.date }}</td>
                <td>
                    <form action="{% url 'teacher:student_notable_update' notable.pk %}" method="get">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-primary" {% if report.writer != request.uesr %}disabled{% endif %}>編集</button>
                    </form>
                </td>
                <td>
                    <form action="{% url 'teacher:student_notable_delete' notable.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-danger" {% if report.writer != request.uesr %}disabled{% endif %}>削除</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">データがありません。</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}