api/urls.py
from django.urls import path
from .views.accounts import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomUserLoginView

urlpatterns = [
    path('', CustomUserLoginView.as_view(), name='login'),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('owner/', include('owner.urls')),
    path('parent/<int:pk>/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
]

owner/urls.py
from django.urls import path
from .views import OwnerDashboardView
from accounts.views import CustomUserActivateView, CustomUserDeleteView, ChangePasswordView, CustomUserProfileView
from students.views import StudentNotableDeleteView, StudentNotableUpdateView, StudentNotableCreateView, StudentStatusUpdateView, StudentSelectView, OwnerStudentListView, OwnerStudentDetailView, OwnerStudentDetailUpdateView
from report_card.views import ReportCardDetailView, ReportCardUpdateView, BatchReportCardSelectView, BatchReportCardUpdateView
from regular_lesson.views import RegularLessonListView, RegularLessonCreateView, RegularLessonDeleteView, RegularLessonUpdateView, RegularLessonCancelView
from special_lesson.views import SpecialLessonCreateView, SpecialLessonListView, SpecialLessonDetailView, SpecialLessonAdminCreateView, SpecialLessonDeleteView, SpecialLessonAdminUpdateView, SpecialLessonAdminDeleteView, SpecialLessonPrintView
from shift.views import ShiftSelectView, ShiftTemplateView, ShiftTemplateUpdateView, ShiftDetailDisplayView, ShiftDetailView, ShiftDetailUpdateView, ShiftDetailReloadView, ShiftLessonCreateView, ShiftLessonDeleteView, ShiftTeacherShiftCreateView, ShiftTeacherShiftDeleteView, ShiftDeleteView
from report.views import OwnerSubmitReportListView, SubmitReportUpdateView, SubmitReportDeleteView, ReportListView
from vocabulary_test.views import VocabularyTestDetailView, VocabularyTestUpdateView
from test_result.views import AverageScoreListView, AverageScoreCreateView, TestResultDetailView, TestResultUpdateView, BatchTestResultUpdateView, AverageScoreUpdateView
from teacher_shift.views import FixedShiftListView, FixedShiftCreateView, SalaryPDFView, FixedShiftDeleteView, FixedShiftUpdateView, FixedShiftCancelView, SalaryCreateView, SalaryListView, SalaryUpdateView, SalaryDeleteView
from invoice.views import InvoicePDFView, InvoiceListView, InvoiceDeleteView, InvoiceUpdateView, PaidInvoiceListView, InvoiceCreateView
from year_schedule.views import OwnerYearScheduleView, EventCreateView, EventDeleteView, PrintMonthScheduleView, PrintSelectView
from file.views import OwnerFileListView, FileDetailView, FileDeleteView
from update_grade.views import UpdateStudentListView, UpdateStudentToMiddleView, UpdateStudentToHighView, UpdateStudentToGradView, UpdateShiftTemplateView, UpdateRegularLessonListView, UpdateFixedShiftListView, UpdateRegularLessonContinueView, UpdateFixedShiftDeleteView, UpdateFixedShiftUpdateView, UpdateFixedShiftContinueView, UpdateRegularLessonDeleteView, UpdateRegularLessonUpdateView
from teacher.views import TeacherListView, TeacherStatusUpdateView

app_name = 'owner'

urlpatterns = [
    path('', OwnerDashboardView.as_view(), name='dashboard'),

    path('account/', CustomUserProfileView.as_view(), name='account_profile'),
    path('account/change_password/', ChangePasswordView.as_view(), name='account_change_password'),

    path('<int:pk>/activate/', CustomUserActivateView.as_view(), name='user_activate'),
    path('<int:pk>/delete/', CustomUserDeleteView.as_view(), name='user_delete'),

    path('student/', OwnerStudentListView.as_view(), name='student_list'),
    path('student/<int:pk>', OwnerStudentDetailView.as_view(), name='student_detail'),
    path('student/<int:pk>/update', OwnerStudentDetailUpdateView.as_view(), name='student_detail_update'),

    path('student/<int:pk>/status', StudentStatusUpdateView.as_view(), name='student_status_update'),
    path('student/<int:pk>/notable/create/', StudentNotableCreateView.as_view(), name='student_notable_create'),
    path('student/<int:pk>/notable/update/', StudentNotableUpdateView.as_view(), name='student_notable_update'),
    path('student/<int:pk>/notable/delete/', StudentNotableDeleteView.as_view(), name='student_notable_delete'),

    path('student/<int:pk>/select/', StudentSelectView.as_view(), name='document_select'),
    path('student/<int:pk>/test_result/', TestResultDetailView.as_view(), name='test_result_detail'),
    path('student/<int:pk>/test_result/update/', TestResultUpdateView.as_view(), name='test_result_edit'),
    path('student/<int:pk>/report/', ReportListView.as_view(), name='report_detail'),
    path('student/<int:pk>/report_card/', ReportCardDetailView.as_view(), name='report_card_detail'), 
    path('student/<int:pk>/report_card/update/', ReportCardUpdateView.as_view(), name='report_card_edit'),
    path('student/<int:pk>/vocabulary_test/', VocabularyTestDetailView.as_view(), name='vocabulary_test_detail'),
    path('studnet/<int:pk>/vocabulary_test/update/', VocabularyTestUpdateView.as_view(), name='vocabulary_test_edit'),

    path('submit_report/', OwnerSubmitReportListView.as_view(), name='report_form_data'),
    path('submit_report/<int:pk>/edit/', SubmitReportUpdateView.as_view(), name='report_update'),
    path('submit_report/delete/', SubmitReportDeleteView.as_view(), name='report_delete_rows'),

    path('teacher/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher/<int:pk>/status/', TeacherStatusUpdateView.as_view(), name='teacher_status_update'),

    path('regular/', RegularLessonListView.as_view(), name='regular_list'),
    path('regular/create/', RegularLessonCreateView.as_view(), name='regular_create'),
    path('regular/update/', RegularLessonUpdateView.as_view(), name='regular_update'),
    path('regular/<int:pk>/cancel', RegularLessonCancelView.as_view(), name='regular_cancel'),
    path('regular/<int:pk>/delete/', RegularLessonDeleteView.as_view(), name='regular_delete'),

    path('fixed_shift/', FixedShiftListView.as_view(), name='fixed_shift_list'),
    path('fixed_shift/create', FixedShiftCreateView.as_view(), name='fixed_shift_create'),
    path('fixed_shift/update/', FixedShiftUpdateView.as_view(), name='fixed_shift_update'),
    path('fixed_shift/<int:pk>/cancel/', FixedShiftCancelView.as_view(), name='fixed_shift_cancel'),
    path('fixed_shift/<int:pk>/delete/', FixedShiftDeleteView.as_view(), name='fixed_shift_delete'),

    path('special/', SpecialLessonListView.as_view(), name='special_list'),
    path('special/create/', SpecialLessonCreateView.as_view(), name='special_create'),
    path('special/<int:pk>/', SpecialLessonDetailView.as_view(), name='special_detail'),
    path('special/<int:pk>/print/', SpecialLessonPrintView.as_view(), name='special_print'),
    path('special/<int:pk>/delete/', SpecialLessonDeleteView.as_view(), name='special_delete'),
    path('special/admin/<int:pk>/update/', SpecialLessonAdminUpdateView.as_view(), name='special_admin_edit'),
    path('special/admin/<int:pk>/create/', SpecialLessonAdminCreateView.as_view(), name='special_admin_create'),
    path('special/admin/<int:pk>/delete/', SpecialLessonAdminDeleteView.as_view(), name='special_admin_delete'),

    path('shift/', ShiftSelectView.as_view(), name='shift_select'),
    path('shift/template/', ShiftTemplateView.as_view(), name='shift_template'),
    path('shift/temdplate/update/', ShiftTemplateUpdateView.as_view(), name='shift_template_update'),
    path('shift/detail/<int:year>/<int:week>/<int:day>/', ShiftDetailView.as_view(), name='shift_detail'),
    path('shift/detail/<int:year>/<int:week>/<int:day>/reload/', ShiftDetailReloadView.as_view(), name='shift_reload'),
    path('shift/detail/update/', ShiftDetailUpdateView.as_view(), name='shift_update'),
    path('shift/detail/lesson/create/', ShiftLessonCreateView.as_view(), name='shift_transfer_lesson'),
    path('shift/detail/lesson/delete/<int:lesson_pk>/<int:relation_num>/<int:unauthorized_absence>/', ShiftLessonDeleteView.as_view(), name='shift_absence_lesson'),
    path('shift/detail/tacher_shift/create/', ShiftTeacherShiftCreateView.as_view(), name='shift_teacher_add'),
    path('shift/detail/teacher_shift/delete/<int:teacher_shift_pk>/', ShiftTeacherShiftDeleteView.as_view(), name='shift_teacher_absence'),
    path('shift/detail/<int:year>/<int:week>/delete/', ShiftDeleteView.as_view(), name='shift_delete'),
    path('shift/detail/display/<int:year>/<int:week>/<int:day>/', ShiftDetailDisplayView.as_view(), name='shift_display'),

    path('salary/', SalaryListView.as_view(), name='salary_list'),
    path('salary/create/', SalaryCreateView.as_view(), name='salary_create'),
    path('salary/update/', SalaryUpdateView.as_view(), name='update_salary'),
    path('salary/delete/<int:pk>/', SalaryDeleteView.as_view(), name='delete_salary'),
    path('salary/pdf/', SalaryPDFView.as_view(), name='salary_show'),

    path('invoice/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/create/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/<int:pk>/delete/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoice/<int:pk>/update/', InvoiceUpdateView.as_view(), name='invoice_update'),
    
    path('invoice/pdf/', InvoicePDFView.as_view(), name='invoice_pdf'),

    path('paid_invoice/', PaidInvoiceListView.as_view(), name='paid_invoice'),

    path('test_result/', AverageScoreListView.as_view(), name='average_score_list'),
    path('test_result/create/', AverageScoreCreateView.as_view(), name='average_score_create'),
    path('test_result/<int:pk>/update/', AverageScoreUpdateView.as_view(), name='average_score_update'),
    path('test_result/<int:pk>/batch/update/', BatchTestResultUpdateView.as_view(), name='test_result_form'),

    path('report_card/', BatchReportCardSelectView.as_view(), name='report_card_semester'),
    path('report_card/<int:semester>/update/', BatchReportCardUpdateView.as_view(), name='report_card_form'),

    path('file/', OwnerFileListView.as_view(), name='file_list'),
    path('file/<int:pk>', FileDetailView.as_view(), name='file_detail'),
    path('file/<int:pk>/delete', FileDeleteView.as_view(), name='file_delete'),

    path('year_schedule/', OwnerYearScheduleView.as_view(), name='year_schedule_calendar'),
    path('year_schedule/add/', EventCreateView.as_view(), name='year_schedule_add'),

parent/urls.py
from django.urls import path
from .views import ParentDashboardView, SwitchStudentView
from accounts.views import StudentSignUpView
from report_card.views import ReportCardDetailView
from report.views import ReportListView
from vocabulary_test.views import VocabularyTestDetailView
from test_result.views import TestResultDetailView
from regular_lesson.views import ParentLessonListView
from notification.views import NotificationListView
from special_lesson.views import SpecialLessonListView, SpecialLessonStudentRequestFormView
from year_schedule.views import ParentYearScheduleView
from file.views import FileDetailView, FileListView
from accounts.views import CustomUserProfileView, ChangePasswordView

app_name = 'parent'

urlpatterns = [
    # path('', ParentDashboardView.as_view(), name='dashboard'),

    path('account/', CustomUserProfileView.as_view(), name='account_profile'),
    path('account/change_password/', ChangePasswordView.as_view(), name='account_change_password'),

    path('test_result/', TestResultDetailView.as_view(), name='test_result_detail'),

    path('report/', ReportListView.as_view(), name='report_detail'),

    path('report_card/', ReportCardDetailView.as_view(), name='report_card_detail'), 

    path('vocabulary_test/', VocabularyTestDetailView.as_view(), name='vocabulary_test_detail'),

    path('switch_student/', SwitchStudentView.as_view(), name='switch_student'),

    path('notification/', NotificationListView.as_view(), name='notification_list'),

    path('lesson/', ParentLessonListView.as_view(), name='schedule_list'),

    path('year_schedule/', ParentYearScheduleView.as_view(), name='dashboard'),

    path('special/', SpecialLessonListView.as_view(), name='special_lesson_list'),
    path('special/<int:special_lesson_pk>/', SpecialLessonStudentRequestFormView.as_view(), name='special_lesson_request'),

    path('file/', FileListView.as_view(), name='file_list'),
    path('file/<int:file_pk>/', FileDetailView.as_view(), name='file_detail'),

    path('student_signup/', StudentSignUpView.as_view(), name='student_signup'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from students.models import Student
from utils.choices import GRADE_CHOICES, SUBJECT_CHOICES

class CustomUser(AbstractUser):
    is_owner = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    # 以下はAbstractUserのフィールドをオーバーライドしてカスタムフィールドを持つようにする
    username = models.CharField(max_length=150, unique=True)  # ユーザー名
    email = models.EmailField(unique=False, blank=True)  # メールアドレス
    first_name = models.CharField(max_length=30, blank=True)  # ユーザーのファーストネーム
    last_name = models.CharField(max_length=150, blank=True)  # ユーザーのラストネーム
    date_joined = models.DateTimeField(auto_now_add=True)  # ユーザーがサイトに参加した日時
    is_active = models.BooleanField(default=True)  # アカウントがアクティブかどうか
    is_staff = models.BooleanField(default=False)  # スタッフ権限を持つかどうか
    is_superuser = models.BooleanField(default=False)  # スーパーユーザーかどうか

    def __str__(self):
        
        # 開発用
        if self.first_name and self.last_name:
            name = self.last_name + ' ' + self.first_name
        else:
            name = self.username
        return name

        # 本来はこちらを使用
        # return f'{self.last_name} {self.first_name}'

class OwnerProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='owner_profile')

    def __str__(self):
        return f'{self.user}'

class TeacherProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='teacher_profile')
    is_withdrawn = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.user}'
    
# 未使用
class TeachingPermission(models.Model):
    teacher_profile = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, blank=True)
    grade = models.IntegerField(choices=GRADE_CHOICES, blank=True)
    subject = models.IntegerField(choices=SUBJECT_CHOICES, blank=True)
    is_teaching = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.teacher_profile} - {self.grade} - {self.subject}'

class ParentProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='parent_profile')
    student = models.ManyToManyField(Student, blank=True, related_name='parent')
    # ユーザーの切り替えに使用
    current_student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True, blank=True, related_name='parent_profiles')

    def __str__(self):
        return f'{self.user} - {self.student} - {self.current_student}'
    

invoice/models.py
from django.db import models
from students.models import Student
from accounts.models import CustomUser

class Invoice(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE) 
    cost_name = models.CharField(max_length=100)
    price = models.IntegerField(null=True, blank=True)  
    date = models.DateField()

    def __str__(self):
        return f'{self.student} {self.cost_name} {self.price} {self.date}'
    
class PaidInvoice(models.Model):
    parent = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateField()
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.parent} {self.date.year} {self.date.month}'

owner/views.py
from datetime import timedelta
import os

from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, FormView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from accounts.decorators import user_type_required
from accounts.models import CustomUser
from notification.models import Notification
from students.models import Student, StudentNotable
from utils.choices import GRADE_CHOICES
from utils.helpers import get_today

@method_decorator(user_type_required(), name='dispatch')
class OwnerDashboardView(ListView):
    template_name = 'owner/dashboard.html'
    model = Notification
    context_object_name = 'notifications'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['customusers'] = CustomUser.objects.filter(is_active=False)
        context['HOST_IP'] = os.environ.get('HOST_IP')
        return context

    def get_queryset(self):
        # 過去30日の通知を表示
        return Notification.objects.filter(user=self.request.user, created_at__gte=(get_today() - timedelta(days=30)))

    def post(self, request, *args, **kwargs):
        pk = request.POST.get('pk')
        notification = Notification.objects.get(pk=pk)
        notification.is_read = True
        notification.save()
        return HttpResponseRedirect(reverse_lazy('owner:dashboard'))

owner/templates/owner/average_score_list.html
{% extends 'owner/base.html' %}

{% block title %}学校テスト{% endblock %}
{% block headline %}データ入力>学校テスト{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-3">
        <div class="col">
            <form method="get" id="filter-form">
                <select id="year" name="year" class="form-select" onchange="this.form.submit()">
                    <option value="">年度を絞り込む</option>
                    {% for year in available_years %}
                        <option value="{{ year }}" {% if year == selected_year %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
            </form>
        </div>
        <div class="col">
            <select class="form-select custom-select" id="schoolFilter" name="school">
                <option value="">学校を絞り込む</option>
                {% for school in schools %}
                    <option value="{{ school.0 }}">{{ school.1 }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col">
            <select class="form-select custom-select" id="gradeFilter" name="grade">
                <option value="">学年を絞り込む</option>
                {% for grade in grades %}
                    <option value="{{ grade.0 }}">{{ grade.1 }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col ms-5">
            <a href="{% url 'owner:average_score_create' %}" class="btn btn-secondary">新規登録</a>
        </div>
    </div>
    <ul class="list-group">
        {% for average_score in average_scores %}
            <li class="list-group-item" data-grade="{{ average_score.grade }}" data-school="{{ average_score.school }}">
                <div class="row align-items-center">
                    <div class="col">{{ average_score.test_name }}</div>
                    <div class="col">{{ average_score.get_school_display }}</div>
                    <div class="col">{{ average_score.get_grade_display }}</div>
                    <div class="col">{{ average_score.date }}</div>
                    <div class="col"><a href="{% url 'owner:average_score_update' average_score.pk %}" class="btn btn-primary">平均点編集</a></div>
                    <div class="col"><a href="{% url 'owner:test_result_form' average_score.pk %}" class="btn btn-danger">一括入力</a></div>
                </div>
            </li>
        {% empty %}
        <li class="list-group-item">データがありません。</li>

        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block script %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        function filterItems() {
            var selectedGrade = document.getElementById("gradeFilter").value;
            var selectedSchool = document.getElementById("schoolFilter").value;
            var rows = document.querySelectorAll(".list-group-item");
        
            rows.forEach(function(row) {
                var gradeCell = row.dataset.grade;
                var schoolCell = row.dataset.school;
        
                if ((selectedGrade === "" || gradeCell === selectedGrade) &&
                    (selectedSchool === "" || schoolCell === selectedSchool)) {
                    row.style.display = "";
                } else {
                    row.style.display = "none";
                }
            });
        }
        document.getElementById("gradeFilter").addEventListener("change", filterItems);
        document.getElementById("schoolFilter").addEventListener("change", filterItems);
        filterItems();
    });
</script>
{% endblock %}

owner/templates/owner/shift_display.html
{% extends 'owner/base.html' %}
{% load custom_tags %}

{% block title %}シフト閲覧{% endblock %}
{% block headline %}<a href="{% url 'owner:shift_select' %}">シフト管理</a>>{{ year }}年第{{ week }}週{% endblock %}

{% block style %}
<style>
    td {
        padding: 0!important;
    }

    hr {
        margin: 0!important;
        color: white;
    }

    .td-row-upper, .td-row-lower {
        margin: 0!important;
        width: 100%;
    }

    .td-row-lower {
        border: 1px black solid;
        height: 28px;
    }

    .td-col {
        border: 1px black solid;
        padding: 0!important;
        height: 52px;
    }
  </style>
{% endblock %}

{% block content %}
    <nav class="d-flex justify-content-center">
        <ul class="pagination">
            {% for date in dates %}
                <li class="page-item"><a class="page-link {% if forloop.counter == day %}active{% endif %}" href="{% url 'owner:shift_display' year week forloop.counter %}">{{ date }}</a></li>
            {% endfor %}
        </ul>
    </nav>
    <div class="container-fluid">
    {% if shifts %}
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    {% for time in time_choices %}
                    <th class="text-center">
                        {{ time }}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% regroup shifts by room as room_list %}
            {% for room in room_list %}
                    <tr>
                        <th class="text-center">{{ room.grouper }}</th>
                        {% for shift in room.list %}
                        <td>
                            <div class="row td-row-upper">
                                {% for i in '1234' %}
                                {% get_lesson shift i as lesson_obj %}
                                <div class="col-6 td-col text-center">
                                    <div class="w-100 h-100 
                                    {% if not lesson_obj %}
                                        bg-white
                                    {% elif lesson_obj.is_rescheduled %}
                                        bg-warning
                                    {% elif lesson_obj.is_temporaly %}
                                        bg-secondary
                                    {% elif lesson_obj.is_regular %}
                                        bg-white
                                    {% else %}
                                        bg-info
                                    {% endif %}
                                        ">
                                        <div class="d-flex justify-content-center">
                                            <span>
                                                {{ lesson_obj.student }}
                                            </span>
                                        </div>
                                        <span>
                                            {{ lesson_obj.get_grade_display }}
                                            {{ lesson_obj.get_subject_display }}
                                            
                                        </span>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>                                                           
                            <div class="row td-row-lower justify-content-center">
                                <div class="d-flex justify-content-center {% if not shift.teacher_shift %}{% if shift.lessons.lesson1 or shift.lessons.lesson2 or shift.lessons.lesson3 or shift.lessons.lesson4 %}bg-danger{% endif %}{% endif %}">
                                    {% if shift.teacher_shift.is_fixed %}
                                    <span>{{ shift.teacher_shift.fixed_shift.teacher }}</span>
                                    {% else %}
                                    <span>{{ shift.teacher_shift.temporaly_shift.teacher }}</span>
                                    {% endif %}
                                </div>
                            </div>
                        </td>
                        {% endfor %}
                    </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h1 class="text-center" style="color: red; font-size: 80px; margin-top: 250px;">休校日</h1>
    {% endif %}
</div>
{% endblock %}

owner/templates/owner/student_detail_update.html
{% extends 'owner/base.html' %}

{% block headline %}<a href="{% url 'owner:student_list' %}">生徒情報</a>><a href="{% url 'owner:student_detail' student.pk %}">個人情報</a>>個人情報編集{% endblock %}

{% block style %}
<style>
    .form-group {
        margin-bottom: 15px;
        display: flex;
        flex-direction: column;
    }

    .form-group label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .form-group input,
    .form-group select,
    .form-group textarea {
        padding: 10px;
        font-size: 16px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 4px;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    .text-danger {
        color: #dc3545;
        margin-top: 5px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1>生徒情報を更新</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.non_field_errors }}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    <div class="text-danger">{{ field.errors }}</div>
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">変更を保存</button>
    </form>
</div>
{% endblock %}

owner/templates/owner/student_status_update.html
{% extends 'owner/base.html' %}

{% block title %}ステータス{% endblock %}
{% block headline %}<a href="{% url 'owner:student_list' %}">生徒情報</a>><a href="{% url 'owner:student_detail' student.pk %}">個人情報</a>>ステータス{% endblock %}

{% block content %}
<div class="container mt-4">
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary mt-3">送信</button>
    </form>
</div>
{% endblock %}

owner/templates/owner/update_to_grad.html
{% extends 'owner/base.html' %}

{% block title %}生徒情報{% endblock %}
{% block headline %}年度切り替え><a href="{% url 'owner:update_student_list' %}">生徒情報</a>>高校3年生{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="form-check">
        {{ form.is_planning_to_withdraw }}
        <label class="form-check-label" for="{{ form.is_planning_to_withdraw.id_for_label }}">退塾予定かどうか</label>
    </div>
    <button type="submit">送信</button>
</form>
{% endblock %}

owner/templates/owner/user_confirm_delete.html
{% extends 'owner/base.html' %}

{% block title %}ホーム{% endblock %}
{% block headline %}ホーム>ユーザーの削除{% endblock %}

{% block content %}
<div class="container w-50">
    <div class="card">
        <div class="card-body">
            <p class="card-text">{{ object }}を削除してもよろしいですか?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">削除</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}