accounts/urls.py
from django.urls import path
from .views import TeacherSignUpView, ParentSignUpView
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = 'accounts'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('teacher_signup/', TeacherSignUpView.as_view(), name='teacher_signup'),
    path('parent_signup/', ParentSignUpView.as_view(), name='parent_signup'),
    path('password_reset/', PasswordResetView.as_view(
        email_template_name='accounts/password_reset_email.html',
        success_url = reverse_lazy("accounts:password_reset_done")
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='accounts_password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='accounts_password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url = reverse_lazy("accounts:password_reset_complete")
    ), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

api/urls.py
from django.urls import path
from .views.accounts import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomUserLoginView

urlpatterns = [
    path('', CustomUserLoginView.as_view(), name='login'),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('owner/', include('owner.urls')),
    path('parent/<int:pk>/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from students.models import Student
from utils.choices import GRADE_CHOICES, SUBJECT_CHOICES

class CustomUser(AbstractUser):
    is_owner = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    # 以下はAbstractUserのフィールドをオーバーライドしてカスタムフィールドを持つようにする
    username = models.CharField(max_length=150, unique=True)  # ユーザー名
    email = models.EmailField(unique=False, blank=True)  # メールアドレス
    first_name = models.CharField(max_length=30, blank=True)  # ユーザーのファーストネーム
    last_name = models.CharField(max_length=150, blank=True)  # ユーザーのラストネーム
    date_joined = models.DateTimeField(auto_now_add=True)  # ユーザーがサイトに参加した日時
    is_active = models.BooleanField(default=True)  # アカウントがアクティブかどうか
    is_staff = models.BooleanField(default=False)  # スタッフ権限を持つかどうか
    is_superuser = models.BooleanField(default=False)  # スーパーユーザーかどうか

    def __str__(self):
        
        # 開発用
        if self.first_name and self.last_name:
            name = self.last_name + ' ' + self.first_name
        else:
            name = self.username
        return name

        # 本来はこちらを使用
        # return f'{self.last_name} {self.first_name}'

class OwnerProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='owner_profile')

    def __str__(self):
        return f'{self.user}'

class TeacherProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='teacher_profile')
    is_withdrawn = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.user}'
    
# 未使用
class TeachingPermission(models.Model):
    teacher_profile = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE, blank=True)
    grade = models.IntegerField(choices=GRADE_CHOICES, blank=True)
    subject = models.IntegerField(choices=SUBJECT_CHOICES, blank=True)
    is_teaching = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.teacher_profile} - {self.grade} - {self.subject}'

class ParentProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='parent_profile')
    student = models.ManyToManyField(Student, blank=True, related_name='parent')
    # ユーザーの切り替えに使用
    current_student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True, blank=True, related_name='parent_profiles')

    def __str__(self):
        return f'{self.user} - {self.student} - {self.current_student}'
    

accounts/views.py
from django.contrib.auth.views import LoginView
from django.forms import BaseModelForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import View, DeleteView, ListView, FormView, TemplateView
from django.views.generic.edit import CreateView
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib import messages 
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.messages.views import SuccessMessageMixin

from .models import OwnerProfile, TeacherProfile, CustomUser
from .forms import CustomUserLoginForm, OwnerCreationForm, TeacherCreationForm, ParentCreationForm, StudentCreationForm, TeacherStatusForm
from .decorators import user_type_required
from students.models import Student
from accounts.models import OwnerProfile, TeacherProfile, ParentProfile
from report_card.models import ReportGrade, SEMESTER_CHOICES
from report_card.models import SUBJECT_CHOICES as REPORT_SUBJECT_CHOICES
from vocabulary_test.models import TestResult, CATEGORY_CHOICES, PROGRAM_CHOICES, COUNT_CHOICES

class CustomUserLoginView(LoginView):
    form_class = CustomUserLoginForm
    template_name = 'accounts/login.html'
    # ログイン時にリダイレクト(開発中はFalse)
    # redirect_authenticated_user = True

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.user.is_authenticated:
            if self.request.user.is_owner:
                return redirect('owner:dashboard')
            elif self.request.user.is_parent:
                pk = self.request.user.parent_profile.current_student.pk
                return redirect('parent:dashboard', pk)
            elif self.request.user.is_teacher:
                return redirect('teacher:dashboard')
        return response
    
class TeacherSignUpView(CreateView):
    form_class = TeacherCreationForm 
    template_name = 'accounts/teacher_signup.html'
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):
        with transaction.atomic():
            teacher = form.save(commit=False)
            teacher.email = form.cleaned_data['username']
            teacher.is_teacher = True
            teacher.is_active = False
            teacher.save()

            # プロファイルの作成
            TeacherProfile.objects.create(user=teacher)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('login') 

class ParentSignUpView(CreateView):
    form_class = ParentCreationForm
    template_name = 'accounts/parent_signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        with transaction.atomic():
            parent = form.save(commit=False)
            parent.email = form.cleaned_data['username']
            parent.is_parent = True
            parent.is_active = False
            parent.save()

            # プロファイルの作成
            parent_profile = ParentProfile.objects.create(user=parent)

            student_last_name = form.cleaned_data['student_last_name']
            student_first_name = form.cleaned_data['student_first_name']
            birth_date = form.cleaned_data['student_birth_date']
            student_elementary_school = form.cleaned_data['student_elementary_school']
            student_school = form.cleaned_data['student_school']
            student_high_school = form.cleaned_data['student_high_school']

            student = Student.objects.create(
                last_name=student_last_name,
                first_name=student_first_name,
                birth_date=birth_date,
                elementary_school=student_elementary_school,
                school=student_school,
                high_school=student_high_school,
            )
            student.update_grade()
            parent_profile.student.add(student)
            parent_profile.current_student = student
            parent_profile.save()

            semester_choices = [semester[0] for semester in SEMESTER_CHOICES]
            subject_choices = [subject[0] for subject in REPORT_SUBJECT_CHOICES]

            for semester in semester_choices:
                for subject in subject_choices:
                    ReportGrade.objects.create(
                        student=student,
                        semester=semester,
                        subject=subject,
                    )

            category_choices = [category[0] for category in CATEGORY_CHOICES]
            program_choices = [program[0] for program in PROGRAM_CHOICES]
            count_choices = [count[0] for count in COUNT_CHOICES]

            for category in category_choices:
                for program in program_choices:
                    for count in count_choices:
                        TestResult.objects.create(
                            student=student,
                            category=category,
                            program=program,
                            count=count,
                        )
            cleaned_data = form.cleaned_data
            print(cleaned_data)

        return super().form_valid(form)
    
    def form_invalid(self, form):
        form.fields['student_school'].initial = form.cleaned_data.get('student_school', None)
        return super().form_invalid(form)

@method_decorator(user_type_required(), name='dispatch')
class StudentSignUpView(CreateView):
    form_class = StudentCreationForm
    template_name = 'parent/student_signup.html'

    def form_valid(self, form):
        parent = self.request.user
        parent_profile = ParentProfile.objects.get(user=parent)

        form.save()

        student = form.instance
        student.update_grade()
        parent_profile.student.add(student)
        # ログイン保持のためここを変更
        # parent_profile.current_student = student
        parent_profile.save()

        semester_choices = [semester[0] for semester in SEMESTER_CHOICES]
        subject_choices = [subject[0] for subject in REPORT_SUBJECT_CHOICES]

        for semester in semester_choices:
            for subject in subject_choices:
                ReportGrade.objects.create(
                    student=student,
                    semester=semester,
                    subject=subject,
                )

        category_choices = [category[0] for category in CATEGORY_CHOICES]
        program_choices = [program[0] for program in PROGRAM_CHOICES]
        count_choices = [count[0] for count in COUNT_CHOICES]

        for category in category_choices:
            for program in program_choices:
                for count in count_choices:
                    TestResult.objects.create(
                        student=student,
                        category=category,
                        program=program,
                        count=count,
                    )

        messages.success(self.request, '送信しました')

        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('parent:dashboard', kwargs={'pk': self.kwargs['pk']})
    
@method_decorator(user_type_required(), name='dispatch')
class CustomUserProfileView(TemplateView):
    def get_template_names(self):
        user_type = 'owner' if self.request.user.is_owner else ('teacher' if self.request.user.is_teacher else 'parent')
        return [f'{user_type}/account_profile.html']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    
@method_decorator(user_type_required(), name='dispatch')
class ChangePasswordView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('login')

    def get_template_names(self):
        user_type = 'owner' if self.request.user.is_owner else ('teacher' if self.request.user.is_teacher else 'parent')
        return [f'{user_type}/account_change_password.html']
    


@method_decorator(user_type_required(), name='dispatch')
class CustomUserActivateView(View):
    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        user = CustomUser.objects.get(pk=pk)
        user.is_active = True
        user.save()
        return HttpResponseRedirect(reverse_lazy('owner:dashboard'))

@method_decorator(user_type_required(), name='dispatch')
class CustomUserDeleteView(DeleteView):
    model = CustomUser
    success_url = reverse_lazy('owner:dashboard')
    template_name = 'owner/user_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.is_parent:
            student = obj.parent_profile.current_student
            student.delete()
        return super().post(request, *args, **kwargs)

api/views/accounts.py
from rest_framework import generics
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import AccessToken, RefreshToken
from ..serializers.accounts import LoginSerializer

class LoginView(generics.GenericAPIView):
    serializer_class = LoginSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        
        # トークン生成
        refresh = RefreshToken.for_user(user)
        
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token),
        })

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <style>
    html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        display: flex;
    }
    .spinner-overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.5);
        z-index: 9999;
    }

    .spinner {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 40px;
        height: 40px;
        margin: auto;
        border-radius: 50%;
        border: 3px solid #ccc;
        border-top-color: #333;
        animation: rotation 2s linear infinite;
    }

    @keyframes rotation {
        0%{ transform:rotate(0);}
        100% {transform: rotate(340deg);}
    }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
    <div class="spinner-overlay d-none" id="spinnerOverlay">
        <div class="spinner"></div>
    </div>
    {% block content %}{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<script>
    const submitButtons = document.querySelectorAll('button[type="submit"]')
    const spinnerOverlay = document.getElementById('spinnerOverlay');
    const form = document.querySelector('form');
    submitButtons.forEach(button => {
        button.addEventListener('click', function() {
            if (form.checkValidity()) {
                spinnerOverlay.classList.remove('d-none');
            };
        });
    });
</script>
{% block script %}{% endblock %}
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}岡崎塾ログイン{% endblock %}

{% block head %}
<style>
.login-header {
  background: #28d;
  padding: 20px;
  font-size: 1.4em;
  font-weight: normal;
  text-align: center;
  text-transform: uppercase;
  color: #fff;
}
</style>
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center w-75">
    <div class="login-form w-75"> <!-- カードを削除 -->
        <div class="d-flex justify-content-center">
        </div>
        <div class="d-flex justify-content-center mt-5">
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                {{ form.non_field_errors }}
                
                <div class="form-group mb-3">
                    <div class="form-field ">
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>
                </div>
                
                <div class="form-group mb-3">
                    <div class="form-field">
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>
                </div>
                <a href="{% url 'accounts:password_reset' %}">パスワードを忘れた場合</a>
                <div class="d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary w-100">ログイン</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/owner_signup.html
{% extends 'accounts/base.html' %}
{% block title %}塾長サインアップ{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header bg-dark">
            <h3 class="text-white">塾長情報登録</h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">登録する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "accounts/base.html" %}

{% block content %}
    <div class="container g-0">
        <div class="row">
            <div class="card g-0 p-0 m-0">
                <div class="card-header justify-content-center">
                    <h3 class="font-weight-light my-4 text-center">パスワードの再設定</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group">
                                <label class="small mb-1" for="id_email">メールアドレス</label>
                                <input type="email" name="email"  class="form-control" autocomplete="email" maxlength="254" required id="id_email">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group mt-0">
                                <button type="submit" class="btn btn-primary mt-3">送信
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <div class="small">
                        <a href="{% url 'login' %}">ログインページに戻る</a><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset confirmation' %}
</div>
{% endblock %}

{% block content %}

{% if validlink %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
  <fieldset class="module aligned">
    <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
    <div class="form-row field-password1">
      {{ form.new_password1.errors }}
      <div class="flex-container">
        <label for="id_new_password1">{% translate 'New password:' %}</label>
        {{ form.new_password1 }}
      </div>
    </div>
    <div class="form-row field-password2">
      {{ form.new_password2.errors }}
      <div class="flex-container">
        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
        {{ form.new_password2 }}
      </div>
    </div>
  </fieldset>
  <div class="submit-row">
    <input type="submit" value="{% translate 'Change my password' %}">
  </div>
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/password_reset_subject.html
Django - Registration/Login App Password Reset

accounts/templates/accounts/teacher_signup.html
{% extends 'accounts/base.html' %}
{% block title %}講師サインアップ{% endblock %}

{% block style %}
<style>
    .errorlist, .errorlist li {
        color: red;
    }
</style>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header bg-dark">
            <h3 class="text-white">講師情報登録</h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">登録する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var lastNameField = document.querySelector('.last-name-field');
        if (lastNameField) {
            lastNameField.focus();
        }
    })
</script>
{% endblock %}