api/urls.py
from django.urls import path
from .views.accounts import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomUserLoginView

urlpatterns = [
    path('', CustomUserLoginView.as_view(), name='login'),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('owner/', include('owner.urls')),
    path('parent/<int:pk>/', include('parent.urls')),
    path('teacher/', include('teacher.urls')),
]

parent/urls.py
from django.urls import path
from .views import ParentDashboardView, SwitchStudentView
from accounts.views import StudentSignUpView
from report_card.views import ReportCardDetailView
from report.views import ReportListView
from vocabulary_test.views import VocabularyTestDetailView
from test_result.views import TestResultDetailView
from regular_lesson.views import ParentLessonListView
from notification.views import NotificationListView
from special_lesson.views import SpecialLessonListView, SpecialLessonStudentRequestFormView
from year_schedule.views import ParentYearScheduleView
from file.views import FileDetailView, FileListView
from accounts.views import CustomUserProfileView, ChangePasswordView

app_name = 'parent'

urlpatterns = [
    # path('', ParentDashboardView.as_view(), name='dashboard'),

    path('account/', CustomUserProfileView.as_view(), name='account_profile'),
    path('account/change_password/', ChangePasswordView.as_view(), name='account_change_password'),

    path('test_result/', TestResultDetailView.as_view(), name='test_result_detail'),

    path('report/', ReportListView.as_view(), name='report_detail'),

    path('report_card/', ReportCardDetailView.as_view(), name='report_card_detail'), 

    path('vocabulary_test/', VocabularyTestDetailView.as_view(), name='vocabulary_test_detail'),

    path('switch_student/', SwitchStudentView.as_view(), name='switch_student'),

    path('notification/', NotificationListView.as_view(), name='notification_list'),

    path('lesson/', ParentLessonListView.as_view(), name='schedule_list'),

    path('year_schedule/', ParentYearScheduleView.as_view(), name='dashboard'),

    path('special/', SpecialLessonListView.as_view(), name='special_lesson_list'),
    path('special/<int:special_lesson_pk>/', SpecialLessonStudentRequestFormView.as_view(), name='special_lesson_request'),

    path('file/', FileListView.as_view(), name='file_list'),
    path('file/<int:file_pk>/', FileDetailView.as_view(), name='file_detail'),

    path('student_signup/', StudentSignUpView.as_view(), name='student_signup'),
]

parent/forms.py
from django import forms
from accounts.models import ParentProfile

class SwitchStudentForm(forms.Form):
    def __init__(self, *args, **kwargs):
        parent_profile = kwargs.pop('parent_profile', None)
        super(SwitchStudentForm, self).__init__(*args, **kwargs)
        self.fields['student'].queryset = parent_profile.student.all()

    student = forms.ModelChoiceField(
        queryset=None,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='生徒',  # ラベルを日本語に変更
        required=True,
    )

parent/views.py
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView

from accounts.decorators import user_type_required
from .forms import SwitchStudentForm
from accounts.models import ParentProfile

@method_decorator(user_type_required(), name='dispatch')
class ParentDashboardView(TemplateView):
    template_name = 'parent/dashboard.html'

@method_decorator(user_type_required(), name='dispatch')
class SwitchStudentView(FormView):
    template_name = 'parent/switch_student.html'
    form_class = SwitchStudentForm
    
    def get_form_kwargs(self):
        kwargs = super(SwitchStudentView, self).get_form_kwargs()
        kwargs['parent_profile'] = ParentProfile.objects.get(user=self.request.user)
        return kwargs

    def form_valid(self, form):
        student_id = form.cleaned_data['student'].id
        parent_profile = ParentProfile.objects.get(user=self.request.user)
        parent_profile.current_student_id = student_id
        parent_profile.save()
        self.student_id = student_id
        return super(SwitchStudentView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('parent:dashboard', kwargs={'pk': self.student_id})

parent/templates/parent/account_change_password.html
{% extends 'parent/base.html' %}

{% block title %}アカウント{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-3">送信</button>
</form>
{% endblock %}

parent/templates/parent/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    {% block head %}{% endblock %}
    
    <!-- Bootstrap JQueryとPopper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <style>
        .logo-image {
            width: 120px;
        }

        .navbar {
            font-size: 12px;
        }

        @media screen and (min-width: 768px) {

        } 

        @media screen and (max-width: 768px) {

        }

        .spinner-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(255, 255, 255, 0.5);
            z-index: 9999;
        }

        .spinner {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 40px;
            height: 40px;
            margin: auto;
            border-radius: 50%;
            border: 3px solid #ccc;
            border-top-color: #333;
            animation: rotation 2s linear infinite;
        }

        @keyframes rotation {
            0%{ transform:rotate(0);}
            100% {transform: rotate(340deg);}
        }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
    <main>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand m-0 p-0" href="{% url 'parent:dashboard' user.parent_profile.current_student.pk %}">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:dashboard' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-house-door" viewBox="0 0 30 20">
                                    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"/>
                                </svg>ホーム
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:schedule_list' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 30 20">
                                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
                                </svg>受講管理
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:test_result_detail' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-calculator" viewBox="0 0 30 20">
                                    <path d="M12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                                    <path d="M4 2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5z"/>
                                </svg>テスト結果
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:report_card_detail' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-card-text" viewBox="0 0 30 20">
                                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                                    <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5M3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8m0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5"/>
                                </svg>通知簿
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:report_detail' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-envelope-paper-fill" viewBox="0 0 30 20">
                                    <path fill-rule="evenodd" d="M6.5 9.5 3 7.5v-6A1.5 1.5 0 0 1 4.5 0h7A1.5 1.5 0 0 1 13 1.5v6l-3.5 2L8 8.75zM1.059 3.635 2 3.133v3.753L0 5.713V5.4a2 2 0 0 1 1.059-1.765M16 5.713l-2 1.173V3.133l.941.502A2 2 0 0 1 16 5.4zm0 1.16-5.693 3.337L16 13.372v-6.5Zm-8 3.199 7.941 4.412A2 2 0 0 1 14 16H2a2 2 0 0 1-1.941-1.516zm-8 3.3 5.693-3.162L0 6.873v6.5Z"/>
                                </svg>授業報告書
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:vocabulary_test_detail' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-alphabet" viewBox="0 0 30 20">
                                    <path d="M2.204 11.078c.767 0 1.201-.356 1.406-.737h.059V11h1.216V7.519c0-1.314-.947-1.783-2.11-1.783C1.355 5.736.75 6.42.69 7.27h1.216c.064-.323.313-.552.84-.552s.864.249.864.771v.464H2.346C1.145 7.953.5 8.568.5 9.496c0 .977.693 1.582 1.704 1.582m.42-.947c-.44 0-.845-.235-.845-.718 0-.395.269-.684.84-.684h.991v.538c0 .503-.444.864-.986.864m5.593.937c1.216 0 1.948-.869 1.948-2.31v-.702c0-1.44-.727-2.305-1.929-2.305-.742 0-1.328.347-1.499.889h-.063V3.983h-1.29V11h1.27v-.791h.064c.21.532.776.86 1.499.86Zm-.43-1.025c-.66 0-1.113-.518-1.113-1.28V8.12c0-.825.42-1.343 1.098-1.343.684 0 1.075.518 1.075 1.416v.45c0 .888-.386 1.401-1.06 1.401Zm2.834-1.328c0 1.47.87 2.378 2.305 2.378 1.416 0 2.139-.777 2.158-1.763h-1.186c-.06.425-.313.732-.933.732-.66 0-1.05-.512-1.05-1.352v-.625c0-.81.371-1.328 1.045-1.328.635 0 .879.425.918.776h1.187c-.02-.986-.787-1.806-2.14-1.806-1.41 0-2.304.918-2.304 2.338z"/>
                                </svg>英単語テスト
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:special_lesson_list' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-credit-card-2-back" viewBox="0 0 30 20">
                                    <path d="M11 5.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5z"/>
                                    <path d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm13 2v5H1V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1m-1 9H2a1 1 0 0 1-1-1v-1h14v1a1 1 0 0 1-1 1"/>
                                </svg>講習授業
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:file_list' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-file-earmark-arrow-down-fill" viewBox="0 0 30 20">
                                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1m-1 4v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 11.293V7.5a.5.5 0 0 1 1 0"/>
                                </svg>ファイル
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:switch_student' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 30 20">
                                    <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2z"/>
                                    <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466"/>
                                </svg>生徒の切り替え
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:student_signup' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 30 20">
                                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                                </svg>兄弟の追加
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'parent:account_profile' user.parent_profile.current_student.pk %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 30 20">
                                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                                </svg>アカウント情報
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid mt-3">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}

            <div class="d-none" id="js-message">
                <div id="message"></div>
                <button type="button" class="btn-close d-none" id="Btn-closed" data-bs-dismiss="alert" aria-label="Close"></button>
                <div class="alert  alert-dismissible fade show alert-primary" id="message-box" role="alert">
                    <span id="message-text"></span>
                    <button type="button" class="btn-close" id="Btn-closed" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
            
            {% block content %}{% endblock %}
        </div>
    </main>
    <div class="spinner-overlay d-none" id="spinnerOverlay">
        <div class="spinner"></div>
    </div>
    <script>
        const submitButtons = document.querySelectorAll('button[type="submit"]')
        const spinnerOverlay = document.getElementById('spinnerOverlay');
        submitButtons.forEach(button => {
            button.addEventListener('click', function() {
                spinnerOverlay.classList.remove('d-none');
            });
        });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

parent/templates/parent/dashboard.html
{% extends 'parent/base.html' %}

{% block title %}保護者ダッシュボード{% endblock %}

{% block content %}

{% endblock %}

parent/templates/parent/file_list.html
{% extends 'parent/base.html' %}

{% block title %}ファイル閲覧{% endblock %}

{% block content %}
<div class="container">
    <h2>ファイル一覧</h2>
    <div class="row">
        {% for file in files %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ file }}</h5>
                    {% if file.file %}
                    <p class="card-text">アップロード日: {{ file.created_at }}</p>
                    <a href="{% url 'parent:file_detail' user.parent_profile.current_student.pk file.pk %}" class="btn btn-primary">表示</a>
                    {% else %}
                    <p class="card-text">No file uploaded</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

parent/templates/parent/notification_list.html
{% extends 'parent/base.html' %}
{% block head %}
<style>
    .notification-filters {
  margin-bottom: 20px;
}

.filter-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  margin-right: 10px;
  cursor: pointer;
}

.notification-cards {
  display: flex;
  flex-direction: column; /* カードを縦に並べる */
  gap: 20px;
}

.notification-card {
  background-color: #fff;
  border: 2px solid transparent; /* 赤線の下に隠れています */
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  position: relative; /* アイコンを配置するため */
}

.notification-card.priority {
  border-color: red; /* 重要なメッセージのカードに赤線を付ける */
}

.priority-badge {
  color: red;
  top: 10px;
  left: 10px;
}

.unread {
  border: 2px solid #007bff;
}

.read-notification-form {
  margin-top: 10px;
}

.read-notification-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 5px 10px;
  cursor: pointer;
}

.read-notification-button:hover {
  background-color: #0056b3;
}

</style>
{% endblock %}
{% block content %}
  <h2>通知センター</h2>
  <form method="GET" action="{% url 'parent:notification_list' user.parent_profile.current_student.pk %}" class="notification-filters">
    <button type="submit" name="is_priority" value="true" class="filter-button">重要</button>
    <button type="submit" name="is_read" value="true" class="filter-button">確認済み</button>
    <button type="submit" name="is_read" value="false" class="filter-button">新規メッセージ</button>
  </form>
  <div class="notification-cards">
    {% for notification in notifications %}
      <div class="notification-card {% if notification.is_priority %}priority{% endif %} {% if not notification.is_read %}unread{% endif %}">
        {% if notification.is_priority %}
          <span class="priority-badge"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z"/>
            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z"/>
          </svg>
          </span>
        {% endif %}
        <strong>{{ notification.message }}</strong>
        {% if not notification.is_read %}
        <form method="POST" action="{% url 'parent:notification_list' user.parent_profile.current_student.pk %}" class="read-notification-form">
          {% csrf_token %}
          <input type="hidden" name="notification_id" value="{{ notification.pk }}">
          <button type="submit" class="read-notification-button">確認する</button>
        </form>
        {% endif %}
      </div>
    {% empty %}
      <div class="notification-card empty">
        <p>メッセージがありません</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

parent/templates/parent/rooms.html
{% extends 'parent/base.html' %}
{% block title %}Rooms | {% endblock %}
{% block content %}
<div class="container-lg mt-10">
    <div class="row">
        {% for room in rooms %}
        <div class="col-lg-12 mb-4">
            <div class="card border-0 rounded-3 shadow">
                <div class="card-body">
                    <h2 class="mb-4 text-2xl font-semibold">{{ room.name }}</h2>
                    {% if room.last_message %}
                        <p>{{ room.last_message.content }}</p>
                    {% endif %}
                    <a href="{% url 'parent:room' user.parent_profile.student.pk room.slug %}" class="btn btn-primary btn-lg rounded-pill px-5">入る</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

parent/templates/parent/special_list.html
{% extends 'parent/base.html' %}

{% block title %}特別講習一覧{% endblock %}

{% block style %}
<style>
    p {
        margin-bottom: 0;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <ul class="list-group">
        {% for special_lesson in special_lessons %}
        <a href="{% url 'parent:special_lesson_request' user.parent_profile.current_student.pk special_lesson.pk %}" class="text-decoration-none">
            <li class="list-group-item text-primary">
                <p>{{ special_lesson.name }}</p>
                <p>{{ special_lesson.start_date|date:"Y年m月d日" }}-{{ special_lesson.end_date|date:"Y年m月d日" }}</p>
            </li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

parent/templates/parent/switch_student.html
{% extends 'parent/base.html' %}

{% block title %}生徒の切り替え{% endblock %}

{% block style %}
<style>
    .custom-card {
    border: 2px solid #ddd;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.custom-card-header {
    background-color: #f8f9fa;
    padding: 10px;
}

.custom-card-body {
    padding: 20px;
}

</style>
{% endblock %}

{% block content %}
    <div class="card custom-card">
        <div class="card-header custom-card-header bg-dark">
            <h1 class="card-title text-center text-white">生徒の切り替え</h1>
        </div>
        <div class="card-body custom-card-body">
            <form method="post" id="switch-student-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" id="submit" class="btn btn-primary" disabled>生徒切替↻</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('switch-student-form');
        const studentField = form.querySelector('#id_student'); // フィールドの ID を使って取得

        function toggleButtonState() {
            const submitButton = form.querySelector('button[type="submit"]');
            if (studentField.value) { // 生徒が選択されている場合は有効にする
                submitButton.removeAttribute('disabled');
            } else { // 生徒が選択されていない場合は無効にする
                submitButton.setAttribute('disabled', 'disabled');
            }
        }

        toggleButtonState(); // ページ読み込み時にボタンの状態を確認

        studentField.addEventListener('change', toggleButtonState); // 生徒の選択が変更されたときにボタンの状態を更新
    });
</script>
{% endblock %}